### ISSUE TITLE
alembic upgrade head fails

### ISSUE THREAD

**Issue by romanchyla** [adsabs/AdsDataSqlSync#39]
I thought the fix will be simple, but I'm now seeing it is using a postgresql datatypes; you should take a look at as I'm not familiar with psql objects

**Comment by romanchyla** [comment]
```
Removing intermediate container d5b25e42f46e
Step 17 : RUN if [ -e alembic.ini ]; then alembic -c ./alembic.ini upgrade head; fi
 ---> Running in 5f76437f4635
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 35972b7b1033, create metrics table
Getting actual config for SQLALCHEMY_URL postgres://data_pipeline:data_pipeline@adswhy:15432/data_pipeline
Traceback (most recent call last):
  File "/usr/local/bin/alembic", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/alembic/config.py", line 450, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/local/lib/python2.7/dist-packages/alembic/config.py", line 444, in main
    self.run_cmd(cfg, options)
  File "/usr/local/lib/python2.7/dist-packages/alembic/config.py", line 427, in run_cmd
    **dict((k, getattr(options, k)) for k in kwarg)
  File "/usr/local/lib/python2.7/dist-packages/alembic/command.py", line 174, in upgrade
    script.run_env()
  File "/usr/local/lib/python2.7/dist-packages/alembic/script/base.py", line 397, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/local/lib/python2.7/dist-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python2.7/dist-packages/alembic/util/compat.py", line 79, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "alembic/env.py", line 87, in <module>
    run_migrations_online()
  File "alembic/env.py", line 80, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python2.7/dist-packages/alembic/runtime/environment.py", line 797, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python2.7/dist-packages/alembic/runtime/migration.py", line 312, in run_migrations
    step.migration_fn(**kw)
  File "/app/alembic/versions/35972b7b1033_create_metrics_table.py", line 22, in upgrade
    sa.Column('id', Integer, primary_key=True),
NameError: global name 'Integer' is not defined
The command '/bin/sh -c if [ -e alembic.ini ]; then alembic -c ./alembic.ini upgrade head; fi' returned a non-zero code: 1
```
